#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTour.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Do_an_OOAD")]
	public partial class QuanLyTourDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertTour(Tour instance);
    partial void UpdateTour(Tour instance);
    partial void DeleteTour(Tour instance);
    partial void InsertDiaDiem_Tour(DiaDiem_Tour instance);
    partial void UpdateDiaDiem_Tour(DiaDiem_Tour instance);
    partial void DeleteDiaDiem_Tour(DiaDiem_Tour instance);
    partial void InsertKhach(Khach instance);
    partial void UpdateKhach(Khach instance);
    partial void DeleteKhach(Khach instance);
    partial void InsertKhachThamGia(KhachThamGia instance);
    partial void UpdateKhachThamGia(KhachThamGia instance);
    partial void DeleteKhachThamGia(KhachThamGia instance);
    partial void InsertLichTrinh_Tour(LichTrinh_Tour instance);
    partial void UpdateLichTrinh_Tour(LichTrinh_Tour instance);
    partial void DeleteLichTrinh_Tour(LichTrinh_Tour instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhieuDangKy(PhieuDangKy instance);
    partial void UpdatePhieuDangKy(PhieuDangKy instance);
    partial void DeletePhieuDangKy(PhieuDangKy instance);
    #endregion
		
		public QuanLyTourDataContext() : 
				base(global::QuanLyTour.Properties.Settings.Default.Do_an_OOADConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<Tour> Tours
		{
			get
			{
				return this.GetTable<Tour>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem_Tour> DiaDiem_Tours
		{
			get
			{
				return this.GetTable<DiaDiem_Tour>();
			}
		}
		
		public System.Data.Linq.Table<Khach> Khaches
		{
			get
			{
				return this.GetTable<Khach>();
			}
		}
		
		public System.Data.Linq.Table<KhachThamGia> KhachThamGias
		{
			get
			{
				return this.GetTable<KhachThamGia>();
			}
		}
		
		public System.Data.Linq.Table<LichTrinh_Tour> LichTrinh_Tours
		{
			get
			{
				return this.GetTable<LichTrinh_Tour>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDangKy> PhieuDangKies
		{
			get
			{
				return this.GetTable<PhieuDangKy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDD;
		
		private string _TenDD;
		
		private string _TinhThanh;
		
		private EntitySet<DiaDiem_Tour> _DiaDiem_Tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDDChanging(int value);
    partial void OnMaDDChanged();
    partial void OnTenDDChanging(string value);
    partial void OnTenDDChanged();
    partial void OnTinhThanhChanging(string value);
    partial void OnTinhThanhChanged();
    #endregion
		
		public DiaDiem()
		{
			this._DiaDiem_Tours = new EntitySet<DiaDiem_Tour>(new Action<DiaDiem_Tour>(this.attach_DiaDiem_Tours), new Action<DiaDiem_Tour>(this.detach_DiaDiem_Tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDD
		{
			get
			{
				return this._TenDD;
			}
			set
			{
				if ((this._TenDD != value))
				{
					this.OnTenDDChanging(value);
					this.SendPropertyChanging();
					this._TenDD = value;
					this.SendPropertyChanged("TenDD");
					this.OnTenDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhThanh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TinhThanh
		{
			get
			{
				return this._TinhThanh;
			}
			set
			{
				if ((this._TinhThanh != value))
				{
					this.OnTinhThanhChanging(value);
					this.SendPropertyChanging();
					this._TinhThanh = value;
					this.SendPropertyChanged("TinhThanh");
					this.OnTinhThanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_DiaDiem_Tour", Storage="_DiaDiem_Tours", ThisKey="MaDD", OtherKey="MaDD")]
		public EntitySet<DiaDiem_Tour> DiaDiem_Tours
		{
			get
			{
				return this._DiaDiem_Tours;
			}
			set
			{
				this._DiaDiem_Tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DiaDiem_Tours(DiaDiem_Tour entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_DiaDiem_Tours(DiaDiem_Tour entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tour")]
	public partial class Tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTour;
		
		private string _TenTour;
		
		private int _GiaTour;
		
		private string _MoTa;
		
		private EntitySet<DiaDiem_Tour> _DiaDiem_Tours;
		
		private EntitySet<LichTrinh_Tour> _LichTrinh_Tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTourChanging(int value);
    partial void OnMaTourChanged();
    partial void OnTenTourChanging(string value);
    partial void OnTenTourChanged();
    partial void OnGiaTourChanging(int value);
    partial void OnGiaTourChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public Tour()
		{
			this._DiaDiem_Tours = new EntitySet<DiaDiem_Tour>(new Action<DiaDiem_Tour>(this.attach_DiaDiem_Tours), new Action<DiaDiem_Tour>(this.detach_DiaDiem_Tours));
			this._LichTrinh_Tours = new EntitySet<LichTrinh_Tour>(new Action<LichTrinh_Tour>(this.attach_LichTrinh_Tours), new Action<LichTrinh_Tour>(this.detach_LichTrinh_Tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTour", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTour
		{
			get
			{
				return this._MaTour;
			}
			set
			{
				if ((this._MaTour != value))
				{
					this.OnMaTourChanging(value);
					this.SendPropertyChanging();
					this._MaTour = value;
					this.SendPropertyChanged("MaTour");
					this.OnMaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTour", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenTour
		{
			get
			{
				return this._TenTour;
			}
			set
			{
				if ((this._TenTour != value))
				{
					this.OnTenTourChanging(value);
					this.SendPropertyChanging();
					this._TenTour = value;
					this.SendPropertyChanged("TenTour");
					this.OnTenTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTour", DbType="Int NOT NULL")]
		public int GiaTour
		{
			get
			{
				return this._GiaTour;
			}
			set
			{
				if ((this._GiaTour != value))
				{
					this.OnGiaTourChanging(value);
					this.SendPropertyChanging();
					this._GiaTour = value;
					this.SendPropertyChanged("GiaTour");
					this.OnGiaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(50)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_DiaDiem_Tour", Storage="_DiaDiem_Tours", ThisKey="MaTour", OtherKey="Matour")]
		public EntitySet<DiaDiem_Tour> DiaDiem_Tours
		{
			get
			{
				return this._DiaDiem_Tours;
			}
			set
			{
				this._DiaDiem_Tours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_LichTrinh_Tour", Storage="_LichTrinh_Tours", ThisKey="MaTour", OtherKey="maTour")]
		public EntitySet<LichTrinh_Tour> LichTrinh_Tours
		{
			get
			{
				return this._LichTrinh_Tours;
			}
			set
			{
				this._LichTrinh_Tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DiaDiem_Tours(DiaDiem_Tour entity)
		{
			this.SendPropertyChanging();
			entity.Tour = this;
		}
		
		private void detach_DiaDiem_Tours(DiaDiem_Tour entity)
		{
			this.SendPropertyChanging();
			entity.Tour = null;
		}
		
		private void attach_LichTrinh_Tours(LichTrinh_Tour entity)
		{
			this.SendPropertyChanging();
			entity.Tour = this;
		}
		
		private void detach_LichTrinh_Tours(LichTrinh_Tour entity)
		{
			this.SendPropertyChanging();
			entity.Tour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem_Tour")]
	public partial class DiaDiem_Tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Matour;
		
		private int _MaDD;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
		private EntityRef<Tour> _Tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMatourChanging(int value);
    partial void OnMatourChanged();
    partial void OnMaDDChanging(int value);
    partial void OnMaDDChanged();
    #endregion
		
		public DiaDiem_Tour()
		{
			this._DiaDiem = default(EntityRef<DiaDiem>);
			this._Tour = default(EntityRef<Tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matour", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Matour
		{
			get
			{
				return this._Matour;
			}
			set
			{
				if ((this._Matour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMatourChanging(value);
					this.SendPropertyChanging();
					this._Matour = value;
					this.SendPropertyChanged("Matour");
					this.OnMatourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDD
		{
			get
			{
				return this._MaDD;
			}
			set
			{
				if ((this._MaDD != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDDChanging(value);
					this.SendPropertyChanging();
					this._MaDD = value;
					this.SendPropertyChanged("MaDD");
					this.OnMaDDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_DiaDiem_Tour", Storage="_DiaDiem", ThisKey="MaDD", OtherKey="MaDD", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.DiaDiem_Tours.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.DiaDiem_Tours.Add(this);
						this._MaDD = value.MaDD;
					}
					else
					{
						this._MaDD = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_DiaDiem_Tour", Storage="_Tour", ThisKey="Matour", OtherKey="MaTour", IsForeignKey=true)]
		public Tour Tour
		{
			get
			{
				return this._Tour.Entity;
			}
			set
			{
				Tour previousValue = this._Tour.Entity;
				if (((previousValue != value) 
							|| (this._Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tour.Entity = null;
						previousValue.DiaDiem_Tours.Remove(this);
					}
					this._Tour.Entity = value;
					if ((value != null))
					{
						value.DiaDiem_Tours.Add(this);
						this._Matour = value.MaTour;
					}
					else
					{
						this._Matour = default(int);
					}
					this.SendPropertyChanged("Tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khach")]
	public partial class Khach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhach;
		
		private string _HoTen;
		
		private string _Diachi;
		
		private string _TenCoQuan;
		
		private string _SDT;
		
		private string _Username;
		
		private string _Pwd;
		
		private EntitySet<PhieuDangKy> _PhieuDangKies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachChanging(int value);
    partial void OnMaKhachChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnTenCoQuanChanging(string value);
    partial void OnTenCoQuanChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPwdChanging(string value);
    partial void OnPwdChanged();
    #endregion
		
		public Khach()
		{
			this._PhieuDangKies = new EntitySet<PhieuDangKy>(new Action<PhieuDangKy>(this.attach_PhieuDangKies), new Action<PhieuDangKy>(this.detach_PhieuDangKies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhach
		{
			get
			{
				return this._MaKhach;
			}
			set
			{
				if ((this._MaKhach != value))
				{
					this.OnMaKhachChanging(value);
					this.SendPropertyChanging();
					this._MaKhach = value;
					this.SendPropertyChanged("MaKhach");
					this.OnMaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCoQuan", DbType="NVarChar(50)")]
		public string TenCoQuan
		{
			get
			{
				return this._TenCoQuan;
			}
			set
			{
				if ((this._TenCoQuan != value))
				{
					this.OnTenCoQuanChanging(value);
					this.SendPropertyChanging();
					this._TenCoQuan = value;
					this.SendPropertyChanged("TenCoQuan");
					this.OnTenCoQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pwd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pwd
		{
			get
			{
				return this._Pwd;
			}
			set
			{
				if ((this._Pwd != value))
				{
					this.OnPwdChanging(value);
					this.SendPropertyChanging();
					this._Pwd = value;
					this.SendPropertyChanged("Pwd");
					this.OnPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_PhieuDangKy", Storage="_PhieuDangKies", ThisKey="MaKhach", OtherKey="MaKhach")]
		public EntitySet<PhieuDangKy> PhieuDangKies
		{
			get
			{
				return this._PhieuDangKies;
			}
			set
			{
				this._PhieuDangKies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.Khach = this;
		}
		
		private void detach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.Khach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachThamGia")]
	public partial class KhachThamGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKh;
		
		private string _Ten;
		
		private string _SDT;
		
		private int _MaPhieuDK;
		
		private EntityRef<PhieuDangKy> _PhieuDangKy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhChanging(int value);
    partial void OnMaKhChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMaPhieuDKChanging(int value);
    partial void OnMaPhieuDKChanged();
    #endregion
		
		public KhachThamGia()
		{
			this._PhieuDangKy = default(EntityRef<PhieuDangKy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKh
		{
			get
			{
				return this._MaKh;
			}
			set
			{
				if ((this._MaKh != value))
				{
					this.OnMaKhChanging(value);
					this.SendPropertyChanging();
					this._MaKh = value;
					this.SendPropertyChanged("MaKh");
					this.OnMaKhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDK", DbType="Int NOT NULL")]
		public int MaPhieuDK
		{
			get
			{
				return this._MaPhieuDK;
			}
			set
			{
				if ((this._MaPhieuDK != value))
				{
					if (this._PhieuDangKy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuDKChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDK = value;
					this.SendPropertyChanged("MaPhieuDK");
					this.OnMaPhieuDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDangKy_KhachThamGia", Storage="_PhieuDangKy", ThisKey="MaPhieuDK", OtherKey="MaPhieuDK", IsForeignKey=true)]
		public PhieuDangKy PhieuDangKy
		{
			get
			{
				return this._PhieuDangKy.Entity;
			}
			set
			{
				PhieuDangKy previousValue = this._PhieuDangKy.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDangKy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDangKy.Entity = null;
						previousValue.KhachThamGias.Remove(this);
					}
					this._PhieuDangKy.Entity = value;
					if ((value != null))
					{
						value.KhachThamGias.Add(this);
						this._MaPhieuDK = value.MaPhieuDK;
					}
					else
					{
						this._MaPhieuDK = default(int);
					}
					this.SendPropertyChanged("PhieuDangKy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichTrinh_Tour")]
	public partial class LichTrinh_Tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLichtring;
		
		private int _maTour;
		
		private System.DateTime _NgayDi;
		
		private System.DateTime _NgayKetthuc;
		
		private EntitySet<PhieuDangKy> _PhieuDangKies;
		
		private EntityRef<Tour> _Tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLichtringChanging(int value);
    partial void OnMaLichtringChanged();
    partial void OnmaTourChanging(int value);
    partial void OnmaTourChanged();
    partial void OnNgayDiChanging(System.DateTime value);
    partial void OnNgayDiChanged();
    partial void OnNgayKetthucChanging(System.DateTime value);
    partial void OnNgayKetthucChanged();
    #endregion
		
		public LichTrinh_Tour()
		{
			this._PhieuDangKies = new EntitySet<PhieuDangKy>(new Action<PhieuDangKy>(this.attach_PhieuDangKies), new Action<PhieuDangKy>(this.detach_PhieuDangKies));
			this._Tour = default(EntityRef<Tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichtring", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLichtring
		{
			get
			{
				return this._MaLichtring;
			}
			set
			{
				if ((this._MaLichtring != value))
				{
					this.OnMaLichtringChanging(value);
					this.SendPropertyChanging();
					this._MaLichtring = value;
					this.SendPropertyChanged("MaLichtring");
					this.OnMaLichtringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTour", DbType="Int NOT NULL")]
		public int maTour
		{
			get
			{
				return this._maTour;
			}
			set
			{
				if ((this._maTour != value))
				{
					if (this._Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaTourChanging(value);
					this.SendPropertyChanging();
					this._maTour = value;
					this.SendPropertyChanged("maTour");
					this.OnmaTourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDi", DbType="Date NOT NULL")]
		public System.DateTime NgayDi
		{
			get
			{
				return this._NgayDi;
			}
			set
			{
				if ((this._NgayDi != value))
				{
					this.OnNgayDiChanging(value);
					this.SendPropertyChanging();
					this._NgayDi = value;
					this.SendPropertyChanged("NgayDi");
					this.OnNgayDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetthuc", DbType="Date NOT NULL")]
		public System.DateTime NgayKetthuc
		{
			get
			{
				return this._NgayKetthuc;
			}
			set
			{
				if ((this._NgayKetthuc != value))
				{
					this.OnNgayKetthucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetthuc = value;
					this.SendPropertyChanged("NgayKetthuc");
					this.OnNgayKetthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Tour_PhieuDangKy", Storage="_PhieuDangKies", ThisKey="MaLichtring", OtherKey="MaLichtrinh")]
		public EntitySet<PhieuDangKy> PhieuDangKies
		{
			get
			{
				return this._PhieuDangKies;
			}
			set
			{
				this._PhieuDangKies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tour_LichTrinh_Tour", Storage="_Tour", ThisKey="maTour", OtherKey="MaTour", IsForeignKey=true)]
		public Tour Tour
		{
			get
			{
				return this._Tour.Entity;
			}
			set
			{
				Tour previousValue = this._Tour.Entity;
				if (((previousValue != value) 
							|| (this._Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tour.Entity = null;
						previousValue.LichTrinh_Tours.Remove(this);
					}
					this._Tour.Entity = value;
					if ((value != null))
					{
						value.LichTrinh_Tours.Add(this);
						this._maTour = value.MaTour;
					}
					else
					{
						this._maTour = default(int);
					}
					this.SendPropertyChanged("Tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh_Tour = this;
		}
		
		private void detach_PhieuDangKies(PhieuDangKy entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh_Tour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _TenNV;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private System.Nullable<bool> _Chucvu;
		
		private string _Username;
		
		private string _Pwd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnChucvuChanging(System.Nullable<bool> value);
    partial void OnChucvuChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPwdChanging(string value);
    partial void OnPwdChanged();
    #endregion
		
		public NhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(50)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="Bit")]
		public System.Nullable<bool> Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pwd", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pwd
		{
			get
			{
				return this._Pwd;
			}
			set
			{
				if ((this._Pwd != value))
				{
					this.OnPwdChanging(value);
					this.SendPropertyChanging();
					this._Pwd = value;
					this.SendPropertyChanged("Pwd");
					this.OnPwdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDangKy")]
	public partial class PhieuDangKy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhach;
		
		private System.DateTime _Ngaylap;
		
		private System.Nullable<bool> _TinhTrang;
		
		private int _MaPhieuDK;
		
		private int _MaLichtrinh;
		
		private EntitySet<KhachThamGia> _KhachThamGias;
		
		private EntityRef<Khach> _Khach;
		
		private EntityRef<LichTrinh_Tour> _LichTrinh_Tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachChanging(int value);
    partial void OnMaKhachChanged();
    partial void OnNgaylapChanging(System.DateTime value);
    partial void OnNgaylapChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnMaPhieuDKChanging(int value);
    partial void OnMaPhieuDKChanged();
    partial void OnMaLichtrinhChanging(int value);
    partial void OnMaLichtrinhChanged();
    #endregion
		
		public PhieuDangKy()
		{
			this._KhachThamGias = new EntitySet<KhachThamGia>(new Action<KhachThamGia>(this.attach_KhachThamGias), new Action<KhachThamGia>(this.detach_KhachThamGias));
			this._Khach = default(EntityRef<Khach>);
			this._LichTrinh_Tour = default(EntityRef<LichTrinh_Tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhach", DbType="Int NOT NULL")]
		public int MaKhach
		{
			get
			{
				return this._MaKhach;
			}
			set
			{
				if ((this._MaKhach != value))
				{
					if (this._Khach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachChanging(value);
					this.SendPropertyChanging();
					this._MaKhach = value;
					this.SendPropertyChanged("MaKhach");
					this.OnMaKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaylap", DbType="Date NOT NULL")]
		public System.DateTime Ngaylap
		{
			get
			{
				return this._Ngaylap;
			}
			set
			{
				if ((this._Ngaylap != value))
				{
					this.OnNgaylapChanging(value);
					this.SendPropertyChanging();
					this._Ngaylap = value;
					this.SendPropertyChanged("Ngaylap");
					this.OnNgaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDK", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhieuDK
		{
			get
			{
				return this._MaPhieuDK;
			}
			set
			{
				if ((this._MaPhieuDK != value))
				{
					this.OnMaPhieuDKChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDK = value;
					this.SendPropertyChanged("MaPhieuDK");
					this.OnMaPhieuDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLichtrinh", DbType="Int NOT NULL")]
		public int MaLichtrinh
		{
			get
			{
				return this._MaLichtrinh;
			}
			set
			{
				if ((this._MaLichtrinh != value))
				{
					if (this._LichTrinh_Tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLichtrinhChanging(value);
					this.SendPropertyChanging();
					this._MaLichtrinh = value;
					this.SendPropertyChanged("MaLichtrinh");
					this.OnMaLichtrinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDangKy_KhachThamGia", Storage="_KhachThamGias", ThisKey="MaPhieuDK", OtherKey="MaPhieuDK")]
		public EntitySet<KhachThamGia> KhachThamGias
		{
			get
			{
				return this._KhachThamGias;
			}
			set
			{
				this._KhachThamGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khach_PhieuDangKy", Storage="_Khach", ThisKey="MaKhach", OtherKey="MaKhach", IsForeignKey=true)]
		public Khach Khach
		{
			get
			{
				return this._Khach.Entity;
			}
			set
			{
				Khach previousValue = this._Khach.Entity;
				if (((previousValue != value) 
							|| (this._Khach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khach.Entity = null;
						previousValue.PhieuDangKies.Remove(this);
					}
					this._Khach.Entity = value;
					if ((value != null))
					{
						value.PhieuDangKies.Add(this);
						this._MaKhach = value.MaKhach;
					}
					else
					{
						this._MaKhach = default(int);
					}
					this.SendPropertyChanged("Khach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Tour_PhieuDangKy", Storage="_LichTrinh_Tour", ThisKey="MaLichtrinh", OtherKey="MaLichtring", IsForeignKey=true)]
		public LichTrinh_Tour LichTrinh_Tour
		{
			get
			{
				return this._LichTrinh_Tour.Entity;
			}
			set
			{
				LichTrinh_Tour previousValue = this._LichTrinh_Tour.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh_Tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh_Tour.Entity = null;
						previousValue.PhieuDangKies.Remove(this);
					}
					this._LichTrinh_Tour.Entity = value;
					if ((value != null))
					{
						value.PhieuDangKies.Add(this);
						this._MaLichtrinh = value.MaLichtring;
					}
					else
					{
						this._MaLichtrinh = default(int);
					}
					this.SendPropertyChanged("LichTrinh_Tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachThamGias(KhachThamGia entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDangKy = this;
		}
		
		private void detach_KhachThamGias(KhachThamGia entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDangKy = null;
		}
	}
}
#pragma warning restore 1591
